### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by staroider** [staroids/community#10]
Many machine learning related projects leverage GPU.

https://github.com/staroids/community/issues/8 will be a requirement to support GPU.

**Comment by staroider** [comment]
`gpu-1` instance type is available on AWS cloud location. (we're working on GCP, too)

```
kind: Pod
apiVersion: v1
metadata:
  name: ..
  labels:
    pod.staroid.com/isolation: dedicated
    pod.staroid.com/instance-type: gpu-1
```

`gpu-1` instance has 1x V100 GPU with 16GB mem, 8 core cpu and 61GB system memory.
